/**
 * `media` module inputs (T-034) — upload metadata and alt text.
 *
 * What this schema does **not** do is decide that a file is safe. §A-10.3
 * requires a byte-level MIME sniff, and the client-declared `mimeType` here is
 * a claim, not evidence — T-037 checks the actual bytes and rejects a mismatch.
 * A `.png` extension and a `image/png` header cost an attacker nothing.
 *
 * Alt text is required in Bangla for the same reason the site has a language
 * policy at all: an image with no alt text is invisible to a screen reader, and
 * §A-13.1 gates every PR on `axe-core`.
 */

import {
  dbId,
  LIMITS,
  multilineText,
  naturalCode,
  plainText,
  strictObject,
  translationSet,
} from "@/lib/validation/primitives";
import { z } from "zod";

/** `media_assets.bucket` — `CHECK (bucket IN ('public','private'))`. */
export const MEDIA_BUCKETS = ["public", "private"] as const;
export const mediaBucket = z.enum(MEDIA_BUCKETS);

/**
 * Upload metadata, as the client presents it.
 *
 * `byteSize` mirrors `CHECK (byte_size > 0)`; the 25 MB ceiling is a product
 * limit, not a column one — a school notice PDF that exceeds it is a scan that
 * should have been compressed.
 */
export const mediaUploadSchema = strictObject({
  bucket: mediaBucket.default("public"),
  originalFilename: plainText(255).nullish(),
  // A claim to be verified against the bytes by T-037, never trusted as-is.
  mimeType: z
    .string()
    .trim()
    .toLowerCase()
    .regex(
      /^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*$/,
      "Must be a MIME type",
    ),
  byteSize: z
    .union([z.bigint(), z.number().int(), z.string().regex(/^\d+$/)])
    .transform((value) => BigInt(value))
    .refine((value) => value > 0n, "Must be a non-empty file")
    .refine((value) => value <= 25n * 1024n * 1024n, "Must be 25 MB or smaller"),
  widthPx: z.number().int().positive().nullish(),
  heightPx: z.number().int().positive().nullish(),
  translations: translationSet({
    altText: plainText(LIMITS.text),
    caption: multilineText(LIMITS.text),
  }),
});

/** Editing an existing asset's descriptive text — the bytes are immutable. */
export const mediaMetadataSchema = strictObject({
  id: dbId,
  translations: translationSet({
    altText: plainText(LIMITS.text),
    caption: multilineText(LIMITS.text),
  }),
});

/** `media_variants` — generated by the pipeline (T-101), not posted by a client. */
export const mediaVariantSchema = strictObject({
  mediaAssetId: dbId,
  variantCode: naturalCode,
  storageKey: z.string().trim().min(1).max(512),
  mimeType: z.string().trim().toLowerCase().min(1).max(128),
  byteSize: z
    .union([z.bigint(), z.number().int(), z.string().regex(/^\d+$/)])
    .transform((value) => BigInt(value))
    .refine((value) => value > 0n, "Must be a non-empty file"),
  widthPx: z.number().int().positive().nullish(),
  heightPx: z.number().int().positive().nullish(),
});

export const mediaDeleteSchema = strictObject({ id: dbId });

export type MediaUploadInput = z.infer<typeof mediaUploadSchema>;
export type MediaMetadataInput = z.infer<typeof mediaMetadataSchema>;
